# Generated by Django 6.0.4 on 2026-04-24 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_news_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='celebrity',
            options={'verbose_name': 'Celebrity', 'verbose_name_plural': 'Celebrities'},
        ),
        migrations.AlterModelOptions(
            name='movietheater',
            options={'verbose_name_plural': 'Movie theater movies'},
        ),
        migrations.AlterModelOptions(
            name='movietv',
            options={'verbose_name': 'Movie TV', 'verbose_name_plural': 'Movie TV'},
        ),
    ]
