# Generated by Django 6.0.4 on 2026-05-01 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_celebrity_options_alter_movietheater_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traileritem',
            name='trailer_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
